org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.caching=false
org.gradle.configuration-cache=false

# Prevent KSP / compiler in-process crashes
kotlin.compiler.execution.strategy=out-of-process
ksp.run.in.process=false

# Allow builds without local google-services.json
googleServices.missing.passthrough=true
